version: "2"

services:
  universal_robot:
    build:
      context: .
      args:
        host_ip: '192.168.1.133'
    labels:
      - com.nvidia.volumes.needed="nvidia_driver"
    container_name: universal_robot
    hostname: universal_robot
    privileged: true
    ports:
         - "50007:50007"
         - "50001:50001"
         - "30002:30002"
    environment:
      - "DISPLAY=$DISPLAY" 
      - "QT_X11_NO_MITSHM=1"
      - "ROS_HOSTNAME=universal_robot"
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - "PATH=/usr/local/nvidia/bin:${PATH}"
      - "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}"
      - "UR_IP=192.168.1.148"
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/udev/rules.d:/etc/udev/rules.d"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$PWD:/catkin_ws/src/universal_robot"
    command: roslaunch ur5 ur5.launch simulation:="true" limited:="true"
    depends_on:
      - rosmaster

  # ros master
  rosmaster:
    image: xihelm/kinetic:kinect
    container_name: rosmaster
    ports:
         - "11311:11311"
    command:
      - roscore
